name: CI build

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  CROSS_CONTAINER_ENGINE: podman

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            "aarch64-unknown-linux-musl",
            "arm-unknown-linux-musleabi",
            "arm-unknown-linux-musleabihf",
            "armv5te-unknown-linux-musleabi",
            "armv7-unknown-linux-musleabi",
            "armv7-unknown-linux-musleabihf",
            "i686-pc-windows-gnu",
            "i686-unknown-linux-musl",
            "mips-unknown-linux-musl",
            "mipsel-unknown-linux-musl",
            "x86_64-pc-windows-gnu",
            "x86_64-unknown-freebsd",
            "x86_64-unknown-linux-musl",
            "x86_64-unknown-netbsd",
          ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly --component rustfmt,clippy
          rustup default nightly
          rustup target add ${{matrix.target}}
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Check format
        run: |
          cargo fmt --all -- --check
      - name: Run clippy
        run: |
          cross clippy --all-targets --locked --target ${{matrix.target}} -- -D warnings
      - name: Run clippy (All features)
        run: |
          cross clippy --locked --all-features --target ${{matrix.target}} -- -D warnings
      - name: Build
        run: |
          cross build -Z build-std=std,panic_abort --release --target ${{matrix.target}}
