name: CI build

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  CROSS_CONTAINER_ENGINE: podman

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            "aarch64-apple-darwin",
            "aarch64-linux-android",
            "aarch64-unknown-linux-musl",
            "arm-unknown-linux-musleabi",
            "arm-unknown-linux-musleabihf",
            "armv5te-unknown-linux-musleabi",
            "armv7-unknown-linux-musleabi",
            "armv7-unknown-linux-musleabihf",
            "i586-unknown-linux-musl",
            "i686-pc-windows-gnu",
            "i686-unknown-freebsd",
            "i686-unknown-linux-musl",
            "mips64el-unknown-linux-gnuabi64",
            "mips64-unknown-linux-gnuabi64",
            "mipsel-unknown-linux-musl",
            "mips-unknown-linux-musl",
            "powerpc64le-unknown-linux-gnu",
            "powerpc64-unknown-linux-gnu",
            "powerpc-unknown-linux-gnu",
            "riscv64gc-unknown-linux-gnu",
            "s390x-unknown-linux-gnu",
            "sparc64-unknown-linux-gnu",
            "x86_64-apple-darwin",
            "x86_64-linux-android",
            "x86_64-pc-windows-gnu",
            "x86_64-unknown-dragonfly",
            "x86_64-unknown-freebsd",
            "x86_64-unknown-linux-musl",
            "x86_64-unknown-netbsd",
          ]
        include:
          - runner: "ubuntu-22.04"
          - toolchain: "stable"
          - buildFlags: "--release"
          - target: "aarch64-apple-darwin"
            runner: "macos-12"
          - target: "x86_64-apple-darwin"
            runner: "macos-12"
          - target: "x86_64-unknown-dragonfly"
            toolchain: "nightly"
            buildFlags: "-Z build-std=std,panic_abort --release"

    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust
        run: |
          rustup set profile minimal
          rustup toolchain install ${{matrix.toolchain}}
          rustup default ${{matrix.toolchain}}
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: |
          cross build ${{matrix.buildFlags}} --target ${{matrix.target}}
      - name: Check if build succeeded
        run: |
          shopt -s extglob
          [[ -x target/${{matrix.target}}/release/rust_unciv_server?(.exe) ]]
          shopt -u extglob
