name: CI build

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  CROSS_CONTAINER_ENGINE: podman

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            "aarch64-unknown-linux-musl",
            "arm-unknown-linux-musleabi",
            "arm-unknown-linux-musleabihf",
            "armv5te-unknown-linux-musleabi",
            "armv7-unknown-linux-musleabi",
            "armv7-unknown-linux-musleabihf",
            "i686-pc-windows-gnu",
            "i686-unknown-linux-musl",
            "mips-unknown-linux-musl",
            "mipsel-unknown-linux-musl",
            "x86_64-pc-windows-gnu",
            "x86_64-sun-solaris",
            "x86_64-unknown-freebsd",
            "x86_64-unknown-linux-musl",
            "x86_64-unknown-netbsd",
          ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          profile: minimal
          default: true
          override: true
          target: ${{ matrix.target }}
          components: rustfmt, clippy
      - uses: actions-rs/cargo@master
        name: Check format
        with:
          command: fmt
          use-cross: true
          args: --all -- --check
      - uses: actions-rs/cargo@master
        name: Run clippy
        with:
          command: clippy
          use-cross: true
          args: --all-targets --locked --target ${{matrix.target}} -- -D warnings
      - uses: actions-rs/cargo@master
        name: Run clippy (All features)
        with:
          command: clippy
          use-cross: true
          args: --locked --all-features --target ${{matrix.target}} -- -D warnings
      - uses: actions-rs/cargo@master
        name: Build
        with:
          command: build
          use-cross: true
          args: --release --target ${{matrix.target}}
