name: Check format

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-format-${{hashFiles('**/Cargo.lock')}}
      - name: Setup rust
        run: |
          rm /home/runner/.cargo/bin/{rustfmt,cargo-fmt}
          rustup set profile minimal
          rustup toolchain install nightly --component rustfmt,clippy
          rustup default nightly
      - name: Check format
        run: |
          cargo fmt --all -- --check
      - name: Run clippy
        run: |
          cargo clippy --all-targets --locked -- -D warnings
      - name: Run clippy (All features)
        run: |
          cargo clippy --locked --all-features -- -D warnings
