name: Release build

on:
  release:
    types: [created]

env:
  CROSS_CONTAINER_ENGINE: podman

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            "aarch64-unknown-linux-musl",
            "arm-unknown-linux-musleabi",
            "arm-unknown-linux-musleabihf",
            "armv5te-unknown-linux-musleabi",
            "armv7-unknown-linux-musleabi",
            "armv7-unknown-linux-musleabihf",
            "i686-pc-windows-gnu",
            "i686-unknown-linux-musl",
            "mips-unknown-linux-musl",
            "mipsel-unknown-linux-musl",
            "x86_64-pc-windows-gnu",
            "x86_64-unknown-freebsd",
            "x86_64-unknown-linux-musl",
            "x86_64-unknown-netbsd",
          ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly
          rustup default nightly
          rustup target add ${{matrix.target}}
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: |
          cross build --release --target ${{matrix.target}}
      - name: Create tar
        run: |
          mkdir assets
          FILENAME=rust_unciv_server-${{github.event.release.tag_name}}-${{matrix.target}}
          shopt -s extglob
          mv target/${{matrix.target}}/release/rust_unciv_server?(.exe) assets
          cd assets
          tar --format=ustar -cf $FILENAME.tar rust_unciv_server?(.exe)
          rm rust_unciv_server?(.exe)
          shopt -u extglob
          zstd -19 --rm $FILENAME.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: assets/*
