name: Release build

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [ "aarch64-unknown-linux-musl", "armv7-unknown-linux-musleabihf", "arm-unknown-linux-musleabihf", "x86_64-unknown-linux-musl" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
          override: true
          target: ${{ matrix.target }}
          components: rust-src
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          use-cross: true
          args: -Z build-std=std,panic_abort --release --target ${{matrix.target}}
      - name: Create tar
        run: |
          mkdir assets
          FILENAME=rust_unciv_server-${{github.event.release.tag_name}}-${{matrix.target}}
          mv target/${{matrix.target}}/release/rust_unciv_server assets
          cd assets
          tar --format=ustar -cf $FILENAME.tar rust_unciv_server
          rm rust_unciv_server
          zstd -19 $FILENAME.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: assets/*
